name: Pipeline Run

on:
  pull_request:
    types:
      - opened # Trigger on new pull request
      - ready_for_review
      - synchronize    # Trigger when new commits are pushed to the PR
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install

      - name: Run Tests and Coverage
        run:
          poetry run pytest --cov=src/ --cov-report=term-missing --cov-report=html --cov-fail-under=80
          
      - name: Run Lint (Flake8)
        run: poetry run flake8 src/
      
      - name: Generate Documentation
        run: |
          poetry run pdoc -o docs t3_cicd_cli

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: reports/

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
      
      - name: Upload Documentation
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/